from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views
from . import auth_views

router = DefaultRouter()
router.register(r'posts', views.PostViewSet)
router.register(r'tasks', views.TaskViewSet)
router.register(r'products', views.ProductViewSet)

urlpatterns = [
    # Function-based views
    path('', views.dashboard, name='dashboard'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('add-task/', views.add_task, name='add_task'),

    # Auth API endpoints
    path('api/auth/register/', auth_views.api_register, name='api-register'),
    path('api/auth/login/', auth_views.api_login, name='api-login'),
    path('api/auth/profile/', auth_views.api_profile, name='api-profile'),

    # Viewset routes (auto-generated by router)
    path('api/v2/', include(router.urls)),

    # CBV-based post CRUD
    path('posts/', views.PostListView.as_view(), name='post-list'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('posts/new/', views.PostCreateView.as_view(), name='post-create'),
    path('posts/<int:pk>/edit/', views.PostUpdateView.as_view(), name='post-update'),
    path('posts/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
]